{{- if and (eq .Values.storage.type "pvc") (empty .Values.storage.pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    {{- include "oci.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if ne .Values.storage.pvc.storageClassName nil }}
  storageClassName: {{ .Values.storage.pvc.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
{{- end }}
