name: Rust Quality Pipeline for PRs

# Run on every PR regardless of base branch (feature stacks included).
on:
  pull_request:

jobs:
  quality:
    uses: unbounded-tech/workflows-rust/.github/workflows/quality.yaml@e5544be009fd26ebe62401f3145e93ea49780727 # v2.3.0
    with:
      cargo_incremental: true
